name: CI

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  laravel-lint:
    name: Laravel Lint
    runs-on: ubuntu-latest

  js-lint:
    name: JS Lint
    runs-on: ubuntu-latest

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: [laravel-lint]

  laravel-test:
    name: Laravel Tests
    runs-on: ubuntu-latest
    needs: [static-analysis]

  js-test:
    name: JS Tests
    runs-on: ubuntu-latest
    needs: [js-lint]
    
